name:           'Mijndert Stuij'
description:    'Engineer. Runner. Minimalist.'
url:            'https://mijndertstuij.nl'
author:         'Mijndert Stuij'

show_drafts: false

exclude: [README.md, Rakefile, Makefile, .gitignore]
include: [_pages]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed
