name:           Mijndert Stuij
description:    Consulting AWS architect and proponent of simplicity with a focus on highly scalable cloud infrastructure.
url:            'https://mijndert.github.io'
author:         'Mijndert Stuij'

paginate: 10

excerpt_separator: "<!-- more -->"

plugins:
  - jekyll-paginate

# Exclude on build
exclude: [README.md, Rakefile, Makefile, awsenv.sh]

# Include on build
include: [_pages, .htaccess]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed
