name:           'Mijndert Stuij'
description:    'Engineer. Hacker. Minimalist.'
url:            'https://mijndert.dev'
author:         'Mijndert Stuij'

# Exclude on build
exclude: [README.md, Rakefile, Makefile]

# Include on build
include: [_pages]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed
