baseURL = "https://mijndertstuij.nl"
title = "Mijndert Stuij"
theme = "minimal"
languageCode = "en-US"

[params]
  description = "Engineer. Runner. Minimalist."

[permalinks]
  posts = "/thought/:year/:title/"

[markup.goldmark.renderer]
  unsafe = true

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"